# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

# build triggers
on:
#  push:
#   branches: [main, master]
#  pull_request:
  workflow_dispatch:

# this action runs create_acronym_table() to create the glossary
name: run_glossary.yml

permissions: read-all

jobs:
  run_glossary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Make glossary
        run: | # | means there will be multiple lines of code here
          devtools::install_local()
          source('R/utils.R')
          create_acronym_table()
        shell: Rscript {0}
        # next: open a PR with new file
